version: '2'

volumes:
  elasticsearch_data: {}
  logstash_data: {}

networks:
  elstacknet:
    driver: bridge

services:
  elasticsearch:
    image: 'dimaskiddo/alpine:elasticsearch-6.5'
    networks:
      - elstacknet
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - ES_JAVA_OPTS=-Xms512M -Xmx512M
    volumes:
      - elasticsearch_data:/opt/elasticsearch/data
    restart: always

  logstash:
    image: 'dimaskiddo/alpine:logstash-6.5'
    networks:
      - elstacknet
    ports:
      - 9600:9600
      - 5000:5000
    environment:
      - LS_JAVA_OPTS=-Xms512M -Xmx512M
      - LS_INGRESS_PORT=5000
      - ES_URL=http://elasticsearch:9200
    volumes:
      - logstash_data:/opt/logstash/data
    depends_on:
      - elasticsearch
    restart: always
