version: '2'

volumes:
  zookeeper_data: {}
  kafka_data: {}

networks:
  kafkanet:
    driver: bridge

services:
  zookeeper:
    image: 'dimaskiddo/alpine:kafka-2.1'
    networks:
      - kafkanet
    ports:
      - 2181:2181
    command:
      - /usr/local/docker/bin/entrypoint
      - zookeeper-server-start.sh
      - /opt/kafka/config/zookeeper.properties
    volumes:
      - zookeeper_data:/data
    restart: always

  kafka:
    image: 'dimaskiddo/alpine:kafka-2.1'
    networks:
      - kafkanet
    ports:
      - 9092
    environment:
      - KAFKA_CONF_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_TOPICS=docker:1:1
    volumes:
      - kafka_data:/data
    depends_on:
      - zookeeper
    restart: always
