version: '2'

volumes:
  elasticsearch_data: {}

networks:
  apmnet:
    driver: bridge

services:
  elasticsearch:
    image: 'dimaskiddo/alpine:elasticsearch-6.5'
    networks:
      - apmnet
    environment:
      - ES_JAVA_OPTS=-Xms512M -Xmx512M
    volumes:
      - elasticsearch_data:/opt/elasticsearch/data
    restart: always

  kibana:
    image: 'kibana:6.5.4'
    networks:
      - apmnet
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    restart: always

  apm:
    image: 'dimaskiddo/alpine:apm-6.5'
    networks:
      - apmnet
    environment:
      - ES_HOST=elasticsearch
      - ES_PORT=9200
    depends_on:
      - elasticsearch
    restart: always
