FROM dimaskiddo/alpine:base
MAINTAINER Dimas Restu Hidayanto <dimas.restu@student.upi.edu>

# Copying Prequisites Configuration
COPY ./content/ /usr/local/docker/

# Setting-up Permissions
RUN chmod 775 /usr/local/docker/bin/build \
  && /usr/local/docker/bin/build \
  && rm -f /usr/local/docker/bin/build

# Set Volumes Directory
VOLUME /var/cache/squid /var/log/squid

# Expose Ports
EXPOSE 3127 3128 3129

# Set Entrypoint Script
ENTRYPOINT ["/usr/local/docker/bin/entrypoint"]

# Set Executor Script
CMD ["sh","-c","squid -f /etc/squid/squid.conf -NYCd 1 $ARGS"]

# Change Working User to "User"
USER user

# Set Labels Used in OpenShift to Describe the Builder Images
LABEL release=1 \
      vendor="Alpine" \
      summary="Virtual Machine (VM) like container platform with Squid 3.5" \
      maintainer="Dimas Restu Hidayanto <dimas.restu@student.upi.edu>" \
      io.k8s.description="Alpine (3.x) with Squid 3.5" \
      io.k8s.display-name="Alpine (3.x) with Squid 3.5" \
      io.openshift.tags="builder,alpine,squid" \
      io.openshift.expose-services="3127:squid;3128:squid-http;3129:squid-https" \
      io.openshift.non-scalable="false"
